env:
  BUILDKITE_ORG_SLUG: "sander-ginn"
  BUILDKITE_CLUSTER_ID: "fe4c54fc-dfe4-4dc8-bcbb-7962ee9a78b6"
  BUILDKITE_HOSTED_QUEUE_KEY: "default"
  BUILDKITE_SELF_HOSTED_QUEUE_KEY: "local-agents"

steps:
  - label: ":buildkite: Select agent queue"
    key: select-queue
    command: "bash .buildkite/scripts/select-queue.sh"
    secrets:
      DYNAMIC_PIPELINE_GRAPHQL_TOKEN: DYNAMIC_PIPELINE_GRAPHQL_TOKEN
    agents:
      queue: "${BUILDKITE_HOSTED_QUEUE_KEY}"
