steps:
  - label: ":go: Backend format & lint"
    key: backend-lint
    command: "bash .buildkite/scripts/backend-lint.sh"
    plugins:
      - docker#v5.12.0:
          image: "golang:1.24"
          mount-checkout: true
          workdir: /workdir

  - label: ":go: Backend tests & build"
    key: backend-test
    command: "bash .buildkite/scripts/backend-test.sh"
    env:
      CLUBHOUSE_TEST_DATABASE_URL: "postgres://clubhouse_test:clubhouse_test@postgres-test:5432/clubhouse_test?sslmode=disable"
    plugins:
      - docker-compose#v5.5.0:
          run: backend-test
          config: .buildkite/docker-compose.ci.yml

  - label: ":node: Frontend lint, check & test"
    key: frontend
    command: "bash .buildkite/scripts/frontend-checks.sh"
    plugins:
      - docker#v5.12.0:
          image: "node:20-bullseye"
          mount-checkout: true
          workdir: /workdir
